name: CI

on:
  push:
    branches: [ main ]
    
jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      TMDB_KEY: ${{ secrets.TMDB_KEY }}
      TMDB_URL: https://api.themoviedb.org/3
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run eslint
        run: npm run lint
      - name: Commit and push changes if any
        uses: EndBug/add-and-commit@v8
        with:
          message: 'chore: eslint'
  test:
    runs-on: ubuntu-latest
    env:
      TMDB_KEY: ${{ secrets.TMDB_KEY }}
      TMDB_URL: https://api.themoviedb.org/3
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run unit tests
        run: npm run test
      - name: Run e2e tests
        run: npm run test:e2e
